[project]
name = "deepseek-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.107.2",
    "streamlit>=1.49.1",
    "watchdog>=6.0.0",
]
